"use client";

import { useMemo, useState } from "react";
import { Card } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useAppStore } from "@/lib/store";

function formatUsd(n: number): string {
  return `$${n.toFixed(4)}`;
}

export function ChatPanel() {
  const messages = useAppStore((s) => s.messages);
  const addMessage = useAppStore((s) => s.addMessage);
  const clearChat = useAppStore((s) => s.clearChat);

  const results = useAppStore((s) => s.results);
  const selectedHitId = useAppStore((s) => s.selectedHitId);

  const selectedHit = useMemo(
    () => results.find((r) => r.id === selectedHitId) ?? null,
    [results, selectedHitId]
  );

  const [text, setText] = useState("");

  function send() {
    const content = text.trim();
    if (!content) return;

    // user message
    addMessage({ role: "user", content });

    // mock assistant response grounded to selected context (if any)
    if (!selectedHit) {
      addMessage({
        role: "assistant",
        content:
          "I can’t answer from your files yet because no context is selected. Use Search to pick a relevant result, then ask again.",
        citations: [],
        costUsd: 0,
        tokensIn: 0,
        tokensOut: 0,
      });
    } else {
      addMessage({
        role: "assistant",
        content:
          `Here’s a grounded answer based on your selected context from "${selectedHit.filename}".\n\n` +
          `Later, this will be generated by the model using retrieved chunks (RAG).`,
        citations: [
          {
            fileId: selectedHit.fileId,
            filename: selectedHit.filename,
            chunkLabel: selectedHit.chunkLabel,
          },
        ],
        // mock numbers for now; replaced when I integrate OpenAI usage
        costUsd: 0.0023,
        tokensIn: 210,
        tokensOut: 95,
      });
    }

    setText("");
  }

  return (
    <div className="border-l p-4 h-full flex flex-col gap-3">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h2 className="font-semibold">Chat</h2>
          <p className="text-sm text-muted-foreground">
            Ask questions grounded in your documents.
          </p>
        </div>

        <Button variant="outline" size="sm" onClick={clearChat}>
          Clear
        </Button>
      </div>

      <Separator />

      {/* Context badge */}
      <Card className="p-3">
        <div className="text-xs text-muted-foreground mb-1">Active context</div>
        {selectedHit ? (
          <div className="text-sm">
            <span className="font-medium">{selectedHit.filename}</span>{" "}
            <span className="text-muted-foreground">• {selectedHit.chunkLabel}</span>
          </div>
        ) : (
          <div className="text-sm text-muted-foreground">
            None selected. Pick a Search result for grounded answers.
          </div>
        )}
      </Card>

      {/* Messages */}
      <div className="flex-1 min-h-0 overflow-auto space-y-3 pr-1">
        {messages.length === 0 ? (
          <Card className="p-3">
            <div className="text-sm text-muted-foreground">
              Ask something. For best results, select a Search hit first.
            </div>
          </Card>
        ) : (
          messages.map((m) => (
            <div key={m.id} className={m.role === "user" ? "flex justify-end" : "flex justify-start"}>
              <Card className={`p-3 max-w-[92%] ${m.role === "user" ? "bg-muted" : ""}`}>
                <div className="text-xs text-muted-foreground mb-2">
                  {m.role === "user" ? "You" : "Assistant"}
                </div>

                <div className="text-sm whitespace-pre-wrap">{m.content}</div>

                {m.role === "assistant" && (
                  <>
                    {m.citations && m.citations.length > 0 && (
                      <>
                        <Separator className="my-3" />
                        <div className="text-xs font-medium mb-2">Citations</div>
                        <div className="space-y-1">
                          {m.citations.map((c) => (
                            <div key={`${c.fileId}-${c.chunkLabel}`} className="text-xs text-muted-foreground">
                              {c.filename} • {c.chunkLabel}
                            </div>
                          ))}
                        </div>
                      </>
                    )}

                    {(m.costUsd !== undefined || m.tokensIn !== undefined || m.tokensOut !== undefined) && (
                      <>
                        <Separator className="my-3" />
                        <div className="flex items-center justify-between text-xs text-muted-foreground">
                          <div>
                            Tokens: {m.tokensIn ?? 0} in / {m.tokensOut ?? 0} out
                          </div>
                          <div>Cost: {formatUsd(m.costUsd ?? 0)}</div>
                        </div>
                      </>
                    )}
                  </>
                )}
              </Card>
            </div>
          ))
        )}
      </div>

      <Separator />

      {/* Composer */}
      <div className="space-y-2">
        <Textarea
          placeholder='Ask a question… (Tip: select a Search result first)'
          value={text}
          onChange={(e) => setText(e.target.value)}
          rows={3}
          onKeyDown={(e) => {
            if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
              e.preventDefault();
              send();
            }
          }}
        />
        <div className="flex items-center justify-between">
          <div className="text-xs text-muted-foreground">
            Send with Ctrl/⌘ + Enter
          </div>
          <Button onClick={send}>Send</Button>
        </div>
      </div>
    </div>
  );
}
